version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cours-a-la-mosquee
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    image: backend-eduroots:latest
    container_name: backend-eduroots
    restart: always
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data: